name: Recurring Issues
description: Create recurring issues on a schedule.
author: Timothy Willard

inputs:
  config:
    description:
      Either a file path or a YAML string containing the configuration for the
      issues to create.
    required: true
  timezone:
    description: The timezone to use for scheduling (i.e. 'UTC').
    required: false
    default: UTC

outputs:
  issues:
    description: A comma separated list of the issues created by this action.

runs:
  using: node24
  main: dist/index.js
